config/routes.rb
Rails.application.routes.draw do

  root 'kouhit_hubs#index'

  devise_for :users

  resources :lectures, only: [] do
    resources :issues, only: [] do
      resources :discussions, param: :discussion_id do
        collection do
          get :submit
        end
      end
    end
    resources :issues, param: :issue_id
  end
  resources :lectures, param: :lecture_id

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :issue
  belongs_to :user
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :lecture
  belongs_to :user
  has_many :discussions
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  has_many :issues
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :issues
  has_many :discussions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lecture
  before_action :set_issue
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]
  before_action :new, only: [:index]

  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = @issue.discussions.all
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
  end

  # GET /discussions/new
  def new
    @discussion = @issue.discussions.new
  end

  # GET /discussions/1/edit
  def edit
  end

  def submit
    render :index
  end

  # POST /discussions
  # POST /discussions.json
  def create
    @discussion = @issue.discussions.build(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to lecture_issue_discussion_path(discussion_id: @discussion.id), notice: 'Discussion was successfully created.' }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to lecture_issue_discussion_path(discussion_id: @discussion.id), notice: 'Discussion was successfully updated.' }
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to lecture_issue_discussions_url, notice: 'Discussion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discussion
      @discussion = @issue.discussions.find(params[:discussion_id])
    end

    def set_issue
      @issue = @lecture.issues.find(params[:issue_id])
    end

    def set_lecture
      @lecture = Lecture.find(params[:lecture_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_params
      params.require(:discussion).permit(:name, :description, :issue_id, :user_id)
    end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lecture
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = @lecture.issues.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = @lecture.issues.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = @lecture.issues.build(issue_params)
    respond_to do |format|
      if @issue.save
        format.html { redirect_to lecture_issue_path(issue_id: @issue), notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to lecture_issue_path(issue_id: @issue.id), notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to lecture_issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = @lecture.issues.find(params[:issue_id])
    end

    def set_lecture
      @lecture = Lecture.find(params[:lecture_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:name, :status, :lecture_id, :user_id)
    end
end

app/controllers/kouhit_hubs_controller.rb
class KouhitHubsController < ApplicationController
  def index
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lecture, only: [:show, :edit, :update, :destroy]

  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.all
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
      @issues = @lecture.issues.all
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url, notice: 'Lecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:lecture_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      params.require(:lecture).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/kouhit_hubs_helper.rb
module KouhitHubsHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/discussions/_form.html.erb
<%= form_for [@lecture, @issue, @discussion], :html => { :class => "form-horizontal discussion" } do |f| %>

  <% if @discussion.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@discussion.errors.count, "error") %> prohibited this discussion from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @discussion.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <label class="control-label col-lg-2" for="discussion_name">タイトル</label>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <label class="control-label col-lg-2" for="discussion_description">内容</label>
    <div class="col-lg-10">
      <button type="button" id="start_rec" class="btn btn-xs btn-primary btn-rec">録音開始</button>
      <button type="button" id="cancel_rec" class="btn btn-xs btn-danger btn-rec">録音停止</button>
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <label class="control-label col-lg-2" for="discussion_issue_id">質問番号</label>
    <div class="col-lg-10">
      <%= f.text_field :issue_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:issue_id) %>
  </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <input type="submit" name="commit" value="投稿" class="btn btn-primary">
      <a class="btn btn-default" href="/lectures/2/issues/2/discussions"><span class="translation_missing" title="translation missing: ja.helpers.links.cancel">キャンセル</span></a>
    </div>
  </div>

<% end %>

app/views/discussions/edit.html.erb
<%- model_class = Discussion -%>
<div class="page-header">
  <h1>ディスカッションを編集する</h1>
</div>
<%= render :partial => 'form' %>

app/views/discussions/index.html.erb
<%- model_class = Discussion -%>
<div class="page-header">
  <h1>ディスカッション</h1>
</div>

<% @discussions.each do |discussion| %>
<div class="panel panel-default">
	<div class="panel-heading">
        <h4 class="discussion-title"><%= link_to discussion.id, lecture_issue_discussion_path(discussion_id: discussion.id) %>：<%= discussion.name %></h4>
	</div>
	<div class="panel-body">
		<%= discussion.description %>
	</div>
	<div class="panel-footer">
	    <p>投稿者：</p>
		<!-- <#%= discussion.user.email %> -->
		<p>作成日時：<%= discussion.created_at %>　
        <a class="btn btn-default btn-xs" href="/discussions/2/edit"><span class="translation_missing" title="translation missing: ja.helpers.links.edit">編集</span></a>
           <a data-confirm="Are you sure?" class="btn btn-xs btn-danger" rel="nofollow" data-method="delete" href="/discussions/2"><span class="translation_missing" title="translation missing: ja.helpers.links.destroy">削除</span></a>
        </p>
	</div>
</div>
<% end %>

<%= render :partial => 'form' %>

app/views/discussions/new.html.erb
<%- model_class = Discussion -%>
<div class="page-header">
  <h1>ディスカッションの投稿</h1>
</div>
<%= render :partial => 'form' %>

app/views/discussions/show.html.erb
<%- model_class = Discussion -%>
<div class="page-header">
  <h1>ディスカッション</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @discussion.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @discussion.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:issue_id) %>:</strong></dt>
  <dd><%= @discussion.issue_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @discussion.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              lecture_issue_discussions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_lecture_issue_discussion_path(discussion_id: @discussion.id), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              lecture_issue_discussion_path(discussion_id: @discussion.id),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/issues/_form.html.erb
<%= form_for [@lecture, @issue], :html => { :class => "form-horizontal issue" } do |f| %>

  <% if @issue.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @issue.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :status, :class => 'form-control' %>
    </div>
    <%=f.error_span(:status) %>
  </div>
  <div class="form-group">
    <%= f.label :lecture_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lecture_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lecture_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lecture_issues_path(lecture_id: params[:lecture_id]), :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/issues/edit.html.erb
<%- model_class = Issue -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/issues/index.html.erb
<%- model_class = Issue -%>
<div class="page-header">
  <h1>質問一覧</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th>タイトル</th>
      <th>講義ID</th>
      <th>作成日時</th>
      <th>編集 / 削除</th>
    </tr>
  </thead>
  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= link_to issue.id, lecture_issue_path(issue_id: issue.id) %></td>
        <td><%= issue.name %></td>
        <td><%= issue.lecture_id %></td>
        <td><%= issue.created_at %></td>
        <td>
          <a class="btn btn-default btn-xs" href="/lectures/2/issues/2/edit"><span class="translation_missing" title="translation missing: ja.helpers.links.edit">編集</span></a>
          <a data-confirm="Are you sure?" class="btn btn-xs btn-danger" rel="nofollow" data-method="delete" href="/lectures/2/issues/2"><span class="translation_missing" title="translation missing: ja.helpers.links.destroy">削除</span></a>
          <%= link_to 'Discussions', lecture_issue_discussions_path(issue_id: issue.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<a class="btn btn-primary" href="/lectures/2/issues/new"><span class="translation_missing" title="translation missing: ja.helpers.links.new">質問を投稿する</span></a>

app/views/issues/new.html.erb
<%- model_class = Issue -%>
<div class="page-header">
  <h1>新しい質問を投稿</h1>
</div>
<%= render :partial => 'form' %>

app/views/issues/show.html.erb
<%- model_class = Issue -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @issue.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @issue.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lecture_id) %>:</strong></dt>
  <dd><%= @issue.lecture_id %></dd>
</dl>

<%= link_to 'Discussions', lecture_issue_discussions_path(issue_id: @issue.id) %>

<%= link_to t('.back', :default => t("helpers.links.back")),
              lecture_issues_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_lecture_issue_path(issue_id: @issue.id), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              lecture_issue_path(issue_id: @issue.id),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/kouhit_hubs/index.html.erb
<div class="jumbotron jumbotron-lg center-block">
      <div class="background-bg"></div>
      <div class="container">
        <h2>単位をとろう</h2>
        <a class="btn btn-green1 btn-lg" href="/users/sign_in" role="button">ログイン</a>
        <a class="btn btn-green1 btn-lg" href="#" role="button">KougitHubとは</a>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "KougitHub" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <a class="navbar-brand" href="/"></a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "講義一覧", lectures_path %></li>
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <span class="glyphicon glyphicon-user"></span> <%= current_user.email %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <!-- <li><%= link_to 'マイページ', "#" %></li> -->
                  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li class="<%= current_page?(new_user_session_path) ? 'active' : '' %>">
                <%= link_to 'ログイン', new_user_session_path %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-10">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

    <footer class="navbar navbar-default footer">
      <div class="container">
        <div class="navbar-text">
          <span>
            &copy; KougitHub 2016
            <% unless Rails.env.production? %>
            <i>(<%= Rails.env %>)</i>
            <% end %>
          </span>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/layouts/kouhit_hubs.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "KougitHub" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top index-page">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"></a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "講義一覧", lectures_path %></li>
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <span class="glyphicon glyphicon-user"></span> <%= current_user.email %> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <!-- <li><%= link_to 'マイページ', "#" %></li> -->
                  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li class="<%= current_page?(new_user_session_path) ? 'active' : '' %>">
                <%= link_to 'ログイン', new_user_session_path %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <%= bootstrap_flash %>
    <%= yield %>

    <footer class="navbar navbar-default footer">
      <div class="container">
        <div class="navbar-text">
          <span>
            &copy; KougitHub 2016
            <% unless Rails.env.production? %>
            <i>(<%= Rails.env %>)</i>
            <% end %>
          </span>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/lectures/_form.html.erb
<%= form_for @lecture, :html => { :class => "form-horizontal lecture" } do |f| %>

  <% if @lecture.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @lecture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <label class="control-label col-lg-2" for="lecture_name">講義名</label>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <input type="submit" name="commit" value="講義を作成" class="btn btn-primary">
      <a class="btn btn-default" href="/lectures"><span class="translation_missing" title="translation missing: ja.helpers.links.cancel">キャンセル</span></a>
    </div>
  </div>

<% end %>

app/views/lectures/edit.html.erb
<%- model_class = Lecture -%>
<div class="page-header">
  <h1>講義を編集する</h1>
</div>
<%= render :partial => 'form' %>

app/views/lectures/index.html.erb
<%- model_class = Lecture -%>
<div class="page-header">
  <h1>講義一覧</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>講義名</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%=link_to lecture.name, lecture_issues_path(lecture_id: lecture.id)%></td>
        <td><%= link_to '編集', lecture_path(lecture) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "新しい講義を作成する",
            new_lecture_path,
            :class => 'btn btn-primary' %>

app/views/lectures/new.html.erb
<%- model_class = Lecture -%>
<div class="page-header">
  <h1>新しい講義を作成する</h1>
</div>
<%= render :partial => 'form' %>

app/views/lectures/show.html.erb
<%- model_class = Lecture -%>
<div class="page-header">
  <h1><%= @lecture.name %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>作成日:</strong></dt>
  <dd><%= @lecture.created_at %></dd>
  <dt><strong>作成者:</strong></dt>
  <dd><%= @lecture.created_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              lectures_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_lecture_path(@lecture), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              lecture_path(@lecture),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>